apiVersion: apps/v1 # Deployment API version
kind: Deployment
metadata:
  name: survey-app
spec:
  replicas: 3 # Number of pod replicas
  selector:
    matchLabels:
      app: survey-app
  template:
    metadata:
      labels:
        app: survey-app
    spec:
      containers:
        - name: survey-app
          image: karanmonga/survey-app:9 # Docker image with tag
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # Exposed container port
