apiVersion: v1 # Service API version
kind: Service
metadata:
  name: survey-app-service
spec:
  selector:
    app: survey-app # Targets pods with this label
  ports:
    - protocol: TCP
      port: 8080 # Exposed service port
      targetPort: 8080 # Pod's container port
  type: LoadBalancer # Exposes the service externally
